name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Run tests
      run: npm test
      env:
        CI: true
        TWENTYI_API_KEY: ${{ secrets.TWENTYI_API_KEY_TEST }}
        TWENTYI_OAUTH_KEY: ${{ secrets.TWENTYI_OAUTH_KEY_TEST }}
        TWENTYI_COMBINED_KEY: ${{ secrets.TWENTYI_COMBINED_KEY_TEST }}
    
    - name: Check code quality
      run: |
        npm run lint 2>/dev/null || true
        npm run typecheck 2>/dev/null || true