name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Run tests
      run: npm test
      env:
        CI: true
        TWENTYI_API_KEY: ${{ secrets.TWENTYI_API_KEY_TEST }}
        TWENTYI_OAUTH_KEY: ${{ secrets.TWENTYI_OAUTH_KEY_TEST }}
        TWENTYI_COMBINED_KEY: ${{ secrets.TWENTYI_COMBINED_KEY_TEST }}
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/**
          README.md
          LICENSE
        body: |
          ## 20i MCP Server Release ${{ github.ref_name }}
          
          ### What's Changed
          - See [CHANGELOG.md](https://github.com/Cbrown35/20i-MCP/blob/main/CHANGELOG.md) for details
          
          ### Installation
          ```bash
          npm install 20i-mcp-server@latest
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}